#!/usr/bin/env bash
# This script installs packages necessary for a dwm environment on Void Linux.
# Written by Sam Saint-Pettersen <s dot stpettersen at pm dot me>
#
# wget -q https://playbooks.stpettersen.xyz/void/setup-dwm-void
# bash setup-dwm-void

xbps_pkgs=(
    "ntp"
    "binutils"
    "bind-utils"
    "pam-devel"
    "btop"
    "htop"
    "eza"
    "7zip"
    "tar"
    "xbps"
    "iw"
    "vim"
    "mousepad"
    "bat"
    "git"
    "gcc"
    "tcc"
    "ldc"
    "clang"
    "valgrind"
    "upx"
    "make"
    "xorg"
    "xinit"
    "picom"
    "libX11"
    "libX11-devel"
    "libXinerama"
    "libXinerama-devel"
    "libxcb"
    "libxcb-devel"
    "libXft"
    "libXft-devel"
    "freetype"
    "freetype-devel"
    "feh"
    "alacritty"
    "flameshot"
    "dmenu"
    "wget"
    "curl"
    "jq"
    "xz"
    "tealdeer"
    "fastfetch"
    "patch"
    "keychain"
    "keepassxc"
    "Thunar"
    "opendoas"
    "pulseaudio"
    "dunst"
    "zellij"
    "onefetch"
    "ponymix"
    "ulauncher"
    "notepadqq"
    "docker"
)

git_urls=(
    "https://github.com/stpettersens/neofetch"
    "https://github.com/dylanaraps/pfetch"
    "https://github.com/stpettersens/dwm"
    "https://github.com/stpettersens/dwmblocks"
)

git_pkgs=(
    "neofetch"
    "pfetch"
    "dwm"
    "dwmblocks"
)

check_void_system() {
    cat /etc/os-release | grep Void
    is_void=$?
    if [[ $is_void == 1 ]] then
        echo "This is not a Void system."
        echo "Aborting..."
        exit -1
    fi
    clear
}

update_packages() {
    sudo xbps-install -Syu
}

install_xbps_pkgs() {
    for pkg in "${xbps_pkgs[@]}"
    do
        sudo xbps-install -Sy $pkg
    done
}

install_git_pkgs() {
    i=0
    for pkg in "${git_pkgs[@]}"
    do
        cd ~/BuildFromSrc
        git clone ${git_urls[$i]}
        cd $pkg
        # Apply patch to package's program
        # if it exists.
        if [-e "$pkg.diff" ]; then
            patch $pkg < $pkg.diff
        fi
        if [ -f "brave.diff" && $pkg == "dwm" ]; then
            patch config.h < brave.diff
        fi
        if [ -f "configure" ]; then
            sh configure
        fi
        make all
        sudo make install
        cd ~
        i=$((i+1))
    done
}

install_xdeb() {
    wget -q https://github.com/xdeb-org/xdeb/releases/latest/download/xdeb
    chmod a+x xdeb
    sudo ln -sf ~/xdeb /usr/bin/xdeb
}

install_latest_brave_deb() {
    # Get machine architecture.
    arch=$(uname -m)
    if [ $arch == "x86_64" ]; then
        arch="amd64"
    elif [ $arch == "aarch64" ]; then
        arch="arm64"
    fi

    # Get latest Brave version.
    echo "Downloading latest stable version of Brave..."
    curl "https://api.github.com/repos/brave/brave-browser/releases?per_page=100&page=1" > releases.json
    vers=$(grep "Release" releases.json | head -n 1 | awk '{ print $3 }')
    v=${vers:1}
    rm -f releases.json
    wget "https://github.com/brave/brave-browser/releases/download/${vers}/brave-browser_${v}_${arch}.deb"

    # Convert Debian package to XBPS installable package and install it.
    echo "Installing Brave..."
    xdeb -Sedf brave-browser_${v}_${arch}.deb
    sudo xbps-install -Syu -R ./binpkgs brave-browser
    sudo ln -sf /usr/bin/brave-browser-stable /usr/bin/brave
}

tealdeer_update_cache() {
    tldr --update
}

log_source_pkgs() {
    mkdir -p ~/.s
    for pkg in "${git_pkgs[@]}"
    do
        touch ~/.s/$pkg
    done
}

create_doas_file() {
    echo "permit nopass :wheel" | sudo tee /etc/doas.conf
}

add_xrandr_line_on_vm() {
    sudo dmesg | grep -i hypervisor
    is_vm=$?
    if [[ $is_vm == 0 ]] then
        sed '5s/$/ vm_do &/' ~/.xinitrc
        cp ~/.xinitrc ~/.xsession
    fi
}

init_dir() {
    cd ~
    mkdir -p ~/BuildFromSrc
}

finish() {
    echo "Installed all, done."
}

install_all() {
    check_void_system
    update_packages
    init_dir
    install_xbps_pkgs
    install_git_pkgs
    install_xdeb
    install_latest_brave_deb
    tealdeer_update_cache
    log_source_pkgs
    create_doas_file
    add_xrandr_line_on_vm
    finish
}

install_all
