#!/usr/bin/env bash
# This script installs packages necessary for a dwm environment on Void Linux.
# Written by Sam Saint-Pettersen <s dot stpettersen at pm dot me>
#
# wget -q https://playbooks.stpettersen.xyz/void/setup-dwm-void
# bash setup-dwm-void

xbps_pkgs=(
    "xorg"
    "xauth"
    "ntp"
    "binutils"
    "bind-utils"
    "pam-devel"
    "btop"
    "htop"
    "eza"
    "7zip"
    "tar"
    "iw"
    "vim"
    "mousepad"
    "bat"
    "git"
    "gcc"
    "tcc"
    "ldc"
    "clang"
    "valgrind"
    "upx"
    "make"
    "xorg"
    "xinit"
    "picom"
    "libX11"
    "libX11-devel"
    "libXinerama"
    "libXinerama-devel"
    "libxcb"
    "libxcb-devel"
    "libXft"
    "libXft-devel"
    "freetype"
    "freetype-devel"
    "feh"
    "alacritty"
    "flameshot"
    "dmenu"
    "wget"
    "curl"
    "jq"
    "xz"
    "tealdeer"
    "fastfetch"
    "patch"
    "keychain"
    "keepassxc"
    "Thunar"
    "opendoas"
    "pulseaudio"
    "dunst"
    "zellij"
    "onefetch"
    "ponymix"
    "ulauncher"
    "notepadqq"
    "docker"
)

git_urls=(
    "https://github.com/stpettersens/neofetch"
    "https://github.com/dylanaraps/pfetch"
    "https://github.com/stpettersens/dwm"
    "https://github.com/stpettersens/dwmblocks"
)

git_pkgs=(
    "neofetch"
    "pfetch"
    "dwm"
    "dwmblocks"
)

check_void_system() {
    cat /etc/os-release | grep Void
    is_void=$?
    if [[ $is_void == 1 ]] then
        echo "This is not a Void system."
        echo "Aborting..."
        exit -1
    fi
    clear
}

update_xbps() {
    sudo xbps-install -u xbps
}

update_packages() {
    sudo xbps-install -Syu
}

install_xbps_pkgs() {
    for pkg in "${xbps_pkgs[@]}"
    do
        sudo xbps-install -Sy $pkg
    done
}

install_git_pkgs() {
    i=0
    for pkg in "${git_pkgs[@]}"
    do
        cd ~/BuildFromSrc
        git clone ${git_urls[$i]}
        cd $pkg
        # Apply patch to package's program
        # if it exists.
        if [-e "$pkg.diff" ]; then
            patch $pkg < $pkg.diff
        fi
        if [ -f "brave.diff" && $pkg == "dwm" ]; then
            patch config.h < brave.diff
        fi
        if [ -f "configure" ]; then
            sh configure
        fi
        make all
        sudo make install
        cd ~
        i=$((i+1))
    done
}

install_xdeb() {
    wget -q https://github.com/xdeb-org/xdeb/releases/latest/download/xdeb
    sudo mv xdeb /usr/local/bin
    sudo chmod a+x xdeb
}

install_latest_brave() {
    mkdir -p ~/bin
    curl -LsSf https://gist.githubusercontent.com/stpettersens/ee8821ba1d6d45937b3eb0c841335cb7/raw/c74a15dc81075e2d096f99ec011d2b9f66f6678f/update-brave-void.sh > ~/bin/update-brave-void.sh
    chmod a+x ~/bin/update-brave-void.sh
    ~/bin/update-brave-void.sh
}

tealdeer_update_cache() {
    tldr --update
}

log_source_pkgs() {
    mkdir -p ~/.s
    for pkg in "${git_pkgs[@]}"
    do
        touch ~/.s/$pkg
    done
}

create_doas_file() {
    echo "permit nopass :wheel" | sudo tee /etc/doas.conf
}

add_xrandr_line_on_vm() {
    sudo dmesg | grep -i hypervisor
    is_vm=$?
    if [[ $is_vm == 0 ]] then
        sed '5s/$/ vm_do &/' ~/.xinitrc
        cp ~/.xinitrc ~/.xsession
    fi
}

init_dir() {
    cd ~
    mkdir -p ~/BuildFromSrc
}

finish() {
    echo "Installed all, done."
}

install_all() {
    check_void_system
    update_xbps
    update_packages
    init_dir
    install_xbps_pkgs
    install_git_pkgs
    install_xdeb
    install_latest_brave
    tealdeer_update_cache
    log_source_pkgs
    create_doas_file
    add_xrandr_line_on_vm
    finish
}

install_all
